[consolidatorService.config]
# IP and Port of the Kafka bootstrap node
KAFKA_BOOTSTRAP_NODE = "localhost:9092"

# Azure Event Hub namespace connection
KAFKA_BOOTSTRAP_NODE = "localhost:9092"

# Azure Event Hub connection-string
EVENT_HUB_CONNECTION_STRING = "test-connection"

# Azure Event Hub related to the system-information
SYSTEM_INFO_HUB = "system-info"

# Partitions in `system-info` EventHub which will get notified for websub topic registration/deregistration
REGISTERED_WEBSUB_TOPICS_PARTITION = 0

# Partitions in `system-info` EventHub which stores consolidated websub topics for the hub
CONSOLIDATED_WEBSUB_TOPICS_PARTITION = 1

# Partitions in `system-info` EventHub which will get notified for websub subscription/unsubscription
WEBSUB_SUBSCRIBERS_PARTITION = 2

# Partitions in `system-info` EventHub which is stores consolidated websub subscribers for this server
CONSOLIDATED_WEBSUB_SUBSCRIBERS_PARTITION = 3

# The interval in which Kafka consumers wait for new messages
POLLING_INTERVAL = 10.0

# The period in which Kafka close method waits to complete
GRACEFUL_CLOSE_PERIOD = 5.0
