# WebSub `hub` URL
HUB = "http://localhost:9000/hub"

# WebSub `topic`
TOPIC = "test-topic"

# WebSub `subscriber` callback URL
CALLBACK_URL = "http://localhost:9090/subscriber"

# File where the results are saved
RESULTS_FILE_PATH = "results.csv"
