# WebSub `hub` URL
HUB = {HUB_URL}

## SSL certification for secure connection
SSL_CERT_PATH = {SSL_CERT_PATH}

# WebSub `topic`
TOPIC = "test-topic"

# File where the results are saved
RESULTS_FILE_PATH = {RESULTS_FILE_PATH}
